# Generated by Django 3.2.3 on 2021-06-12 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoxTop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TOP', 'TOPO DE BOLO'), ('BOX', 'CAIXA BOX')], max_length=255)),
                ('theme', models.CharField(max_length=255)),
                ('birthdayName', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor total das Caixas R$')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('storedIn', models.ImageField(blank=True, null=True, upload_to='boxes/', verbose_name='Figura')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Cliente')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='clients/', verbose_name='Foto de Perfil')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Balanço')),
                ('cakeMaker', models.BooleanField(default=False, verbose_name='Boleira')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('deliveryAt', models.DateTimeField(blank=True, null=True, verbose_name='Entregar em')),
                ('delivered', models.BooleanField(default=False, verbose_name='Entregue')),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('downPayment', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True, verbose_name='Entrada R$')),
                ('totalOrder', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True, verbose_name='Total Pedido R$')),
                ('totalPayment', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True, verbose_name='Total Pago R$')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order_control.client', verbose_name='Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createAt', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='PurchasedItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity', models.IntegerField()),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order_control.purchase')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PP', 'PicPay'), ('PIX', 'PIX'), ('CC', 'Cartão de Crédito'), ('CD', 'Cartão de Débito'), ('CASH', 'Dinheiro')], max_length=255)),
                ('createAt', models.DateField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order_control.order')),
            ],
        ),
        migrations.CreateModel(
            name='LoyatyCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('finishedAt', models.DateTimeField(blank=True, null=True)),
                ('giftDate', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order_control.client')),
                ('giftTopOfCake', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='order_control.boxtop')),
            ],
        ),
        migrations.AddField(
            model_name='boxtop',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order_control.order'),
        ),
        migrations.CreateModel(
            name='Adhesive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('loyatyCard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order_control.loyatycard')),
                ('topOfCake', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order_control.boxtop')),
            ],
        ),
    ]
