# Generated by Django 3.2.3 on 2021-06-03 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('PP', 'PicPay'), ('PIX', 'PIX'), ('CC', 'Cartão de Crédito'), ('CD', 'Cartão de Débito'), ('CASH', 'Dinheiro')], max_length=255),
        ),
        migrations.AlterField(
            model_name='purchaseditems',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
