# Generated by Django 3.2.3 on 2021-06-26 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_control', '0002_auto_20210626_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='createAt',
            field=models.DateTimeField(),
        ),
    ]
