# Generated by Django 3.2.3 on 2021-06-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_control', '0004_auto_20210605_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='cakeMaker',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='clients/', verbose_name='Foto de Perfil'),
        ),
    ]
