# Generated by Django 3.2.3 on 2021-07-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_control', '0008_alter_boxtop_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyatycard',
            name='finishedAt',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
