# Generated by Django 3.2.3 on 2021-07-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_control', '0009_alter_loyatycard_finishedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxtop',
            name='storedIn',
            field=models.FileField(blank=True, null=True, upload_to='boxes/', verbose_name='Figura'),
        ),
        migrations.AlterField(
            model_name='client',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='clients/', verbose_name='Foto de Perfil'),
        ),
    ]
