# Generated by Django 3.2.3 on 2021-11-21 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_control', '0011_auto_20210729_2137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boxtop',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='purchaseditems',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='boxtop',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='order_control.order'),
        ),
        migrations.AlterField(
            model_name='boxtop',
            name='type',
            field=models.CharField(choices=[('TOPPER', 'TOPO DE BOLO'), ('BOX', 'CAIXA BOX'), ('TAG', 'TAG'), ('OTHERS', 'OUTROS')], max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client', to='order_control.client', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('PP', 'PicPay'), ('PIX', 'PIX'), ('CC', 'Cartão de Crédito'), ('CD', 'Cartão de Débito'), ('CASH', 'Dinheiro'), ('DCC', 'Depósito Conta Corrente')], max_length=255, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='purchaseditems',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='order_control.purchase'),
        ),
        migrations.AlterUniqueTogether(
            name='boxtop',
            unique_together={('order', 'id')},
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('client', 'id')},
        ),
        migrations.AlterUniqueTogether(
            name='purchaseditems',
            unique_together={('purchase', 'id')},
        ),
    ]
