# Generated by Django 3.2.3 on 2022-01-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_control', '0013_auto_20211121_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxtop',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Valor total R$'),
        ),
    ]
